version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/milmove-app"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/milmove-infra"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/milmove-app-browsers"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/milmove-cypress"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: npm
  directory: "/milmove-cypress"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
- package-ecosystem: docker
  directory: "/milmove-infra-tf13"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
