repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace

-   repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.22.0
    hooks:
    -   id: markdownlint

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
        stages: [commit]
