repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
    -   id: markdownlint

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
        stages: [commit]

- repo: https://github.com/zahorniak/pre-commit-circleci.git
  rev: v0.6
  hooks:
    - id: circleci_validate
      args:
        - .circleci/config.yml
