#!/usr/bin/env bash
set -x -eu -o pipefail

#
# Note on Cache Busting and Build Args: only add `--build-arg` where
# the dockerfile contains steps that require them.
#

# bust cache for apt-get daily
CACHE_APT=$(date '+%Y-%m-%d')

# bust cache for pip when requirements.txt changes
CACHE_PIP=$(shasum -a 256 requirements.txt | cut -f1 -d' ')

docker build --build-arg CACHE_APT="$CACHE_APT" \
             --build-arg CACHE_PIP="$CACHE_PIP" \
             -t milmove/circleci-docker \
             -t milmove/circleci-docker:base \
             .


pushd milmove-app
docker build --build-arg CACHE_APT="$CACHE_APT" \
             --build-arg CACHE_PIP="$CACHE_PIP" \
             -t milmove/circleci-docker:milmove-app \
             .
popd


docker build --build-arg CACHE_APT="$CACHE_APT" \
             --build-arg CACHE_PIP="$CACHE_PIP" \
             -t milmove/circleci-docker:milmove-cypress \
             -f milmove-cypress/Dockerfile .

pushd milmove-infra-tf104
docker build -t milmove/circleci-docker:milmove-infra-tf104 \
             .
popd

pushd milmove-infra-tf112
docker build -t milmove/circleci-docker:milmove-infra-tf112 \
             .
popd

pushd milmove-atlantis
docker build -t milmove/circleci-docker:milmove-atlantis \
             .
popd


pushd milmove-db-export
docker build -t milmove/circleci-docker:milmove-db-export \
             .
popd