#!/usr/bin/env bash
set -x -eu -o pipefail

set +u
if [ -z "$CI" ]; then # protective magick
  echo "This script must be run inside a CI environment."
  exit 0
fi
set -u

#shellcheck disable=SC2010,SC2207
reserved_tags=( $(ls -d -- * | grep milmove ) latest )

for tag in "${reserved_tags[@]}"
do
  shopt -s extglob
  for sha in $CIRCLE_SHA1 ${CIRCLE_BRANCH//+([^A-Za-z0-9-.])/-}
  do
    # README: Since `latest` is reserved for the main Dockerfile, we need to
    # make a special case for it since the other tags names come from the
    # directories in the repository.
    if test "${tag}" == "latest"
    then
      docker tag  milmove/circleci-docker "milmove/circleci-docker:${sha}"
      docker push "milmove/circleci-docker:${sha}"
    else
      docker tag "milmove/circleci-docker:${tag}" "milmove/circleci-docker:${tag}-${sha}"
      docker push "milmove/circleci-docker:${tag}-${sha}"
    fi
  done
done



set +u
# push latest tags on main
if [[ $CIRCLE_BRANCH = main ]]; then
  for tag in "${reserved_tags[@]}"
  do
    if test "${tag}" == "latest"
    then
      docker push milmove/circleci-docker
    else
      docker push "milmove/circleci-docker:${tag}"
    fi
  done
fi
set -u
