#!/bin/bash

#
# A test script to check the docker file
#

set -exu -o pipefail

function test_latest() {
  tag=latest
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" shellcheck --version
  docker run -it "milmove/circleci-docker:${tag}" circleci version
  docker run -it "milmove/circleci-docker:${tag}" aws --version
  docker run -it "milmove/circleci-docker:${tag}" chamber version
  docker run -it "milmove/circleci-docker:${tag}" pre-commit --version

  echo "Passed ${tag}"
}

function test_milmove_app() {
  tag=milmove-app
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" go version
  docker run -it "milmove/circleci-docker:${tag}" go-bindata --version
  docker run -it "milmove/circleci-docker:${tag}" swagger version
  docker run -it "milmove/circleci-docker:${tag}" node --version
  docker run -it "milmove/circleci-docker:${tag}" yarn --version
  docker run -it "milmove/circleci-docker:${tag}" which entr
  docker run -it "milmove/circleci-docker:${tag}" psql --version

  echo "Passed ${tag}"
}

function test_milmove_app_browsers() {
  tag=milmove-app-browsers
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" google-chrome --version
  docker run -it "milmove/circleci-docker:${tag}" chromedriver --version

  echo "Passed ${tag}"
}

function test_milmove_cypress() {
  tag=milmove-cypress
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" yarn cypress version

  echo "Passed ${tag}"
}

function test_milmove_infra_tf103() {
  tag=milmove-infra-tf103
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" find-guardduty-user version
  docker run -it "milmove/circleci-docker:${tag}" terraform --version
  docker run -it "milmove/circleci-docker:${tag}" terraform-docs --version
  docker run -it "milmove/circleci-docker:${tag}" tfsec --version

  echo "Passed ${tag}"
}

function test_milmove_infra_tf104() {
  tag=milmove-infra-tf104
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" find-guardduty-user version
  docker run -it "milmove/circleci-docker:${tag}" terraform --version
  docker run -it "milmove/circleci-docker:${tag}" terraform-docs --version
  docker run -it "milmove/circleci-docker:${tag}" tfsec --version

  echo "Passed ${tag}"
}

function test_milmove_infra_tf15() {
  tag=milmove-infra-tf15
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/circleci-docker:${tag}" find-guardduty-user version
  docker run -it "milmove/circleci-docker:${tag}" terraform --version
  docker run -it "milmove/circleci-docker:${tag}" terraform-docs --version
  docker run -it "milmove/circleci-docker:${tag}" tfsec --version

  echo "Passed ${tag}"
}

for tag in latest milmove-app milmove-app-browsers milmove-cypress milmove-infra-tf103 milmove-infra-tf104 milmove-infra-tf15; do
  echo
  echo "* Testing USER is properly set to 'circleci' on '${tag}' tagged image"
  docker run -it "milmove/circleci-docker:${tag}" bash -xc '[[ $(whoami) = circleci ]]'

  case ${tag} in
    latest)
      test_latest
    ;;
    milmove-app)
      test_milmove_app
    ;;
    milmove-app-browsers)
      test_milmove_app_browsers
    ;;
    milmove-cypress)
      test_milmove_cypress
    ;;
    milmove-infra-tf15)
      test_milmove_infra_tf15
    ;;
    milmove-infra-tf103)
      test_milmove_infra_tf103
    ;;
    milmove-infra-tf104)
      test_milmove_infra_tf104
    ;;
esac

done

echo "Passed."
exit 0
