version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: PST8PDT
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
