version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for reserved branch names
          command: |
            if [[ $CIRCLE_BRANCH = latest || $CIRCLE_BRANCH = milmove-app || $CIRCLE_BRANCH = milmove-app-browsers || $CIRCLE_BRANCH = milmove-cypress || $CIRCLE_BRANCH = milmove-infra-tf15 ]]; then
              echo "Don't use a branch named 'latest', 'milmove-app', 'milmove-app-browsers', 'milmove-cypress', 'milmove-infra-tf15'; these are meaningful tags."
              exit 1
            fi
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build containers
          command: make build

      - run:
          name: Test containers
          command: make test

      - run:
          name: Release container
          command: |
            shopt -s extglob
            for tag in $CIRCLE_SHA1 ${CIRCLE_BRANCH//+([^A-Za-z0-9-.])/-}; do
              # latest
              docker tag  milmove/circleci-docker milmove/circleci-docker:$tag
              docker push milmove/circleci-docker:$tag

              # milmove-app
              docker tag  milmove/circleci-docker:milmove-app milmove/circleci-docker:milmove-app-$tag
              docker push milmove/circleci-docker:milmove-app-$tag

              # milmove-app-browsers
              docker tag  milmove/circleci-docker:milmove-app-browsers milmove/circleci-docker:milmove-app-browsers-$tag
              docker push milmove/circleci-docker:milmove-app-browsers-$tag

              # milmove-cypress
              docker tag  milmove/circleci-docker:milmove-cypress milmove/circleci-docker:milmove-cypress-$tag
              docker push milmove/circleci-docker:milmove-cypress-$tag

              # milmove-infra-tf15
              docker tag  milmove/circleci-docker:milmove-infra-tf15 milmove/circleci-docker:milmove-infra-tf15-$tag
              docker push milmove/circleci-docker:milmove-infra-tf15-$tag

              # milmove-infra-tf103
              docker tag  milmove/circleci-docker:milmove-infra-tf103 milmove/circleci-docker:milmove-infra-tf103-$tag
              docker push milmove/circleci-docker:milmove-infra-tf103-$tag

              # milmove-atlantis
              docker tag  milmove/circleci-docker:milmove-atlantis milmove/circleci-docker:milmove-atlantis-$tag
              docker push milmove/circleci-docker:milmove-atlantis-$tag
            done

            # push default tags on master
            if [[ $CIRCLE_BRANCH = master ]]; then
              docker push milmove/circleci-docker
              docker push milmove/circleci-docker:milmove-app
              docker push milmove/circleci-docker:milmove-app-browsers
              docker push milmove/circleci-docker:milmove-cypress
              docker push milmove/circleci-docker:milmove-infra-tf15
              docker push milmove/circleci-docker:milmove-infra-tf14
              docker push milmove/circleci-docker:milmove-atlantis
            fi
