version: 2
jobs:
  test-branch-name:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for reserved branch names
          command: |
            important_branches=( $(ls -d * | grep milmove) latest )
            for branch in "${important_branches[@]}"
            do
              if test "${CIRCLE_BRANCH}" == ${branch}
              then
                echo "Don't use meaningful tags for a branch name!"
                echo "Don't use a branch named ${branch}."
                exit 1
              fi
            done

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build containers
          command: make build

      - run:
          name: Test containers
          command: make test

      - run:
          name: Release container
          command: |
            shopt -s extglob
            for tag in $CIRCLE_SHA1 ${CIRCLE_BRANCH//+([^A-Za-z0-9-.])/-}; do
              # latest
              docker tag  milmove/circleci-docker milmove/circleci-docker:$tag
              docker push milmove/circleci-docker:$tag

              # milmove-app
              docker tag  milmove/circleci-docker:milmove-app milmove/circleci-docker:milmove-app-$tag
              docker push milmove/circleci-docker:milmove-app-$tag

              # milmove-cypress
              docker tag  milmove/circleci-docker:milmove-cypress milmove/circleci-docker:milmove-cypress-$tag
              docker push milmove/circleci-docker:milmove-cypress-$tag

              # milmove-playwright
              docker tag  milmove/circleci-docker:milmove-playwright milmove/circleci-docker:milmove-playwright-$tag
              docker push milmove/circleci-docker:milmove-playwright-$tag

              # milmove-infra-tf112
              docker tag  milmove/circleci-docker:milmove-infra-tf112 milmove/circleci-docker:milmove-infra-tf112-$tag
              docker push milmove/circleci-docker:milmove-infra-tf112-$tag

              # milmove-infra-tf132
              docker tag  milmove/circleci-docker:milmove-infra-tf132 milmove/circleci-docker:milmove-infra-tf132-$tag
              docker push milmove/circleci-docker:milmove-infra-tf132-$tag

              # milmove-atlantis
              docker tag  milmove/circleci-docker:milmove-atlantis milmove/circleci-docker:milmove-atlantis-$tag
              docker push milmove/circleci-docker:milmove-atlantis-$tag
            done

            # push default tags on main
            if [[ $CIRCLE_BRANCH = main ]]; then
              docker push milmove/circleci-docker
              docker push milmove/circleci-docker:milmove-app
              docker push milmove/circleci-docker:milmove-cypress
              docker push milmove/circleci-docker:milmove-infra-tf112
              docker push milmove/circleci-docker:milmove-infra-tf132
              docker push milmove/circleci-docker:milmove-atlantis
            fi

workflows:
  version: 2
  build-containers:
    jobs:
      - test-branch-name
      - build:
          requires:
            - test-branch-name
          filters:
            branches:
              # NOTE: These branches are ignored because we use them when
              # building containers for the application and infrastructure.
              ignore:
                - latest
                - milmove-app
                - milmove-atlantis
                - milmove-cypress
                - milmove-infra-tf132
                - milmove-infra-tf112
