version: 2
jobs:
  test-branch-name:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for reserved branch names
          command: |
            important_branches=( $(ls -d * | grep milmove) latest )
            for branch in "${important_branches[@]}"
            do
              if test "${CIRCLE_BRANCH}" == ${branch}
              then
                echo "Don't use meaningful tags for a branch name!"
                echo "Don't use a branch named ${branch}."
                exit 1
              fi
            done

  build:
    machine: true
      # TODO: This image is the ARM image, but can't be used yet.
      # image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build containers
          command: make build

      - run:
          name: Test containers
          command: make test

      - run:
          name: Release container
          command: make release

workflows:
  version: 2
  build-containers:
    jobs:
      - test-branch-name
      - build:
          requires:
            - test-branch-name
          filters:
            branches:
              # NOTE: These branches are ignored because we use them when
              # building containers for the application and infrastructure.
              ignore:
                - latest
                - milmove-app
                - milmove-atlantis
                - milmove-cypress
                - milmove-infra-tf132
                - milmove-infra-tf112
