version: 1
update_configs:

  # Keep base image up to date in root and sub directories, batching pull requests weekly
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/milmove-app"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/milmove-app-browsers"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/milmove-cypress"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/milmove-infra"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/milmove-infra-tf13"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/milmove-orders"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"

  # Keep cypress javascript deps up-to-date also
  - package_manager: "javascript"
    directory: "/milmove-cypress"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"

  # Keep python modules up to date in root level, batching pull requests weekly
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
