version: 1
update_configs:
  # Keep base image up to date in root, batching pull requests weekly
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
  # Keep python modules up to date in root & 1 level below, batching pull requests weekly
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "dependencies"
