#!/bin/bash

#
# A script to upgrade all brew formula related to docker files
#

set -exu -o pipefail

brew upgrade \
    awscli \
    chamber \
    circleci \
    go \
    go-bindata \
    nodenv \
    node-build \
    pre-commit \
    shellcheck \
    terraform-docs \
    tfsec \
    tfenv \
    yarn

nodenv install 12.16.3 --skip-existing
nodenv local 12.16.3
tfenv install latest
tfenv use 0.14.9
