#!/bin/bash

#
# A script to upgrade all brew formula related to docker files
#

set -exu -o pipefail

brew upgrade \
    awscli \
    chamber \
    circleci \
    go \
    nodenv \
    node-build \
    pre-commit \
    shellcheck \
    terraform-docs \
    tfsec \
    tfenv \
    yarn

nodenv install --skip-existing
nodenv local
tfenv install latest
tfenv use 0.14.9
