name: Get latest tfsec version

on:
  push:
    branches: [master,  mb-11440-tfsec-updater]

jobs:
  update-tfsec:
    runs-on: ubuntu-latest
    env:
      CURRENT_IMAGE_DIRECTORY: 'milmove-infra-tf112'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ROBOT_MYMOVE_TOKEN }}
      - name: Set release version and current version variables
        id: get-versions
        run: |
          echo ::set-output name=current_tag::$(grep TFSEC_VERSION $CURRENT_IMAGE_DIRECTORY/Dockerfile | head -1 | cut -d'=' -f 2)
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/aquasecurity/tfsec/releases/latest | jq -r ".tag_name[1:]")
      - name: Change release version in Dockerfile
        if: ${{ steps.get-versions.outputs.release_tag != steps.get-versions.outputs.current_tag }}
        id: update-version
        env:
          OLD_VERSION: ${{ steps.get-versions.outputs.current_tag }}
          NEW_VERSION: ${{ steps.get-versions.outputs.release_tag }}
        run: |
          echo $OLD_VERSION
          echo $NEW_VERSION
          cd ${CURRENT_IMAGE_DIRECTORY}
          sed -i --expression='s,${OLD_VERSION},${NEW_VERSION},g' "${CURRENT_IMAGE_DIRECTORY}/Dockerfile"
      - name: set up Git
        if: ${{ steps.get-versions.outputs.release_tag != steps.get-versions.outputs.current_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_MYMOVE_TOKEN }}
          GITHUB_ACTOR_NAME: "robot-mymove"
          GITHUB_ACTOR_EMAIL: "dp3-integrations+github@truss.works"
        run: |
          git config --global user.name "${GITHUB_ACTOR_NAME}"
          git config --global user.email "${GITHUB_ACTOR_EMAIL}"
      - name: Create Pull Request
        if: ${{ steps.get-versions.outputs.release_tag != steps.get-versions.outputs.current_tag }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ROBOT_MYMOVE_TOKEN }}
          commit-message: Update tfsec to new version
          author: ${GITHUB_ACTOR_NAME} <${GITHUB_ACTOR_EMAIL}>
          branch: randombranchname-${{ steps.get-versions.outputs.release_tag }}
          delete-branch: true
          title: Update tfsec Version to ${{ steps.get-versions.outputs.release_tag }}
          body: |
            Automated update from tfsec version ${{ steps.get-versions.outputs.current_tag }} to version ${{ steps.get-versions.outputs.release_tag }}
            Release Notes: https://github.com/aquasecurity/tfsec/releases/tag/v${{ steps.get-versions.outputs.release_tag }}